import { useQuery } from "@tanstack/react-query";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Loader2, ShoppingBag, CheckCircle2, Truck, PackageCheck, Clock3, UserRound } from "lucide-react";
function eventStyle(title:string,type?:string){const s=(title||"").toLowerCase();if(s.includes("livr")||s.includes("delivered"))return{dot:"bg-emerald-500",box:"bg-emerald-50 border-emerald-200 dark:bg-emerald-950/20",icon:PackageCheck,label:"Livraison"};if(s.includes("expédi")||s.includes("ramass")||s.includes("transit")||type==="shipping")return{dot:"bg-violet-500",box:"bg-violet-50 border-violet-200 dark:bg-violet-950/20",icon:Truck,label:"Expédition"};if(s.includes("confirm"))return{dot:"bg-blue-500",box:"bg-blue-50 border-blue-200 dark:bg-blue-950/20",icon:CheckCircle2,label:"Confirmation"};if(s.includes("cré")||type==="created")return{dot:"bg-slate-500",box:"bg-slate-50 border-slate-200 dark:bg-slate-900/30",icon:ShoppingBag,label:"Création"};return{dot:"bg-amber-500",box:"bg-amber-50 border-amber-200 dark:bg-amber-950/20",icon:Clock3,label:"Mise à jour"}}
export function OrderHistoryDialog({order,open,onOpenChange}:{order:any|null;open:boolean;onOpenChange:(v:boolean)=>void}){
 const {data,isLoading,isError}=useQuery<any>({queryKey:["/api/orders",order?.id,"history"],queryFn:async()=>{const r=await fetch(`/api/orders/${order.id}/history`,{credentials:"include"});if(!r.ok)throw new Error("Historique indisponible");return r.json()},enabled:open&&!!order?.id,staleTime:0,retry:1}); const events=data?.events||[];
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-2xl max-h-[86vh] overflow-hidden flex flex-col z-[100]"><DialogHeader><DialogTitle className="text-xl">Historique de la commande {order?.orderNumber?`#${order.orderNumber}`:""}</DialogTitle><DialogDescription>Parcours complet depuis l'entrée de la commande jusqu'à son statut actuel.</DialogDescription></DialogHeader>
 {data?.order&&<div className="rounded-xl border bg-muted/20 p-3 flex flex-wrap gap-x-5 gap-y-1 text-xs"><span><b>Statut actuel:</b> {data.order.currentStatus||"—"}</span>{data.order.shippingProvider&&<span><b>Transporteur:</b> {data.order.shippingProvider}</span>}{data.order.trackingNumber&&<span><b>Tracking:</b> {data.order.trackingNumber}</span>}</div>}
 <div className="overflow-y-auto px-1 py-2">{isLoading?<div className="py-14 flex justify-center"><Loader2 className="w-6 h-6 animate-spin text-primary"/></div>:isError?<div className="py-12 text-center text-sm text-destructive">Impossible de charger l'historique.</div>:events.length===0?<div className="py-12 text-center text-sm text-muted-foreground">Aucun historique enregistré.</div>:<div className="relative ml-3"><div className="absolute left-[11px] top-3 bottom-3 w-px bg-border"/>{events.slice().reverse().map((ev:any)=>{const st=eventStyle(ev.title,ev.type),Icon=st.icon;return <div key={ev.id} className="relative pl-9 pb-4"><div className={`absolute left-0 top-2 w-[23px] h-[23px] rounded-full ${st.dot} flex items-center justify-center ring-4 ring-background`}><Icon className="w-3 h-3 text-white"/></div><div className={`rounded-xl border p-3 ${st.box}`}><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] uppercase tracking-wider font-bold opacity-60">{st.label}</div><div className="font-semibold text-sm mt-0.5">{ev.title}</div></div><time className="text-xs font-medium whitespace-nowrap">{ev.at?new Date(ev.at).toLocaleString("fr-MA",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}):"—"}</time></div>{ev.actor&&<div className="flex items-center gap-1 mt-2 text-xs opacity-70"><UserRound className="w-3 h-3"/>{ev.actor}</div>}</div></div>})}</div>}</div></DialogContent></Dialog>
}